[colors.bright]
black = "#62686c"
blue = "#378dfe"
cyan = "#ff69d7"
green = "#73ffd8"
magenta = "#ae81ff"
red = "#ff54b0"
white = "#5ffbbe"
yellow = "#fcf4ad"

[colors.cursor]
cursor = "#38ff9c"
text = "#000000"

[colors.normal]
black = "#0b3b61"
blue = "#1376f8"
cyan = "#ff5dd4"
green = "#52ffcf"
magenta = "#c792ea"
red = "#ff3a3a"
white = "#15fca2"
yellow = "#fff383"

[colors.primary]
background = "#010b17"
foreground = "#ebddf4"

[colors.selection]
background = "#38ff9c"
text = "#000000"

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 6
y = 6
